// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc771.MyRobot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveLeftDrive;
    public static SpeedController driveRightDrive;
    public static RobotDrive driveRobotDrive;
    public static AnalogInput driveLeftRangeFinder;
    public static Encoder driveLeftDriveQuadEncoder;
    public static Encoder driveRightDriveQuadEncoder;
    public static AnalogInput driveRightRangeFinder;
    public static AnalogGyro driveAnalogGyro;
    public static Encoder intakeShooterQuadEncoder;
    public static SpeedController intakeIntakeMotor;
    public static SpeedController intakeLeftMecanum;
    public static SpeedController intakeRightMecanum;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveLeftDrive = new Talon(1);
        LiveWindow.addActuator("Drive", "LeftDrive", (Talon) driveLeftDrive);
        
        driveRightDrive = new Talon(2);
        LiveWindow.addActuator("Drive", "RightDrive", (Talon) driveRightDrive);
        
        driveRobotDrive = new RobotDrive(driveLeftDrive, driveRightDrive);
        
        driveRobotDrive.setSafetyEnabled(true);
        driveRobotDrive.setExpiration(0.1);
        driveRobotDrive.setSensitivity(0.5);
        driveRobotDrive.setMaxOutput(1.0);

        driveRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        driveLeftRangeFinder = new AnalogInput(1);
        LiveWindow.addSensor("Drive", "LeftRangeFinder", driveLeftRangeFinder);
        
        driveLeftDriveQuadEncoder = new Encoder(0, 1, false, EncodingType.k4X);
        LiveWindow.addSensor("Drive", "LeftDriveQuadEncoder", driveLeftDriveQuadEncoder);
        driveLeftDriveQuadEncoder.setDistancePerPulse(1.0);
        driveLeftDriveQuadEncoder.setPIDSourceType(PIDSourceType.kRate);
        driveRightDriveQuadEncoder = new Encoder(2, 3, false, EncodingType.k4X);
        LiveWindow.addSensor("Drive", "RightDriveQuadEncoder", driveRightDriveQuadEncoder);
        driveRightDriveQuadEncoder.setDistancePerPulse(1.0);
        driveRightDriveQuadEncoder.setPIDSourceType(PIDSourceType.kRate);
        driveRightRangeFinder = new AnalogInput(2);
        LiveWindow.addSensor("Drive", "RightRangeFinder", driveRightRangeFinder);
        
        driveAnalogGyro = new AnalogGyro(0);
        LiveWindow.addSensor("Drive", "AnalogGyro", driveAnalogGyro);
        //driveAnalogGyro.setSensitivity(0.007);
        intakeShooterQuadEncoder = new Encoder(4, 5, false, EncodingType.k4X);
        LiveWindow.addSensor("Intake", "ShooterQuadEncoder", intakeShooterQuadEncoder);
        intakeShooterQuadEncoder.setDistancePerPulse(1.0);
        intakeShooterQuadEncoder.setPIDSourceType(PIDSourceType.kRate);
        intakeIntakeMotor = new Talon(3);
        LiveWindow.addActuator("Intake", "IntakeMotor", (Talon) intakeIntakeMotor);
        
        intakeLeftMecanum = new Talon(4);
        LiveWindow.addActuator("Intake", "LeftMecanum", (Talon) intakeLeftMecanum);
        
        intakeRightMecanum = new Talon(5);
        LiveWindow.addActuator("Intake", "RightMecanum", (Talon) intakeRightMecanum);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
