// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc771.MyRobot.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc771.MyRobot.Robot;

/**
 *
 */
public class DriveWithParams extends Command {

    // BEGIN AUTOGENERATED COwpiDE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private double m_leftMotorSetpoint;
    private double m_rightMotorSetpoint;
    private double m_duration;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DriveWithParams(double leftMotorSetpoint, double rightMotorSetpoint, double duration) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        m_leftMotorSetpoint = leftMotorSetpoint;
        m_rightMotorSetpoint = rightMotorSetpoint;
        m_duration = duration;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.drive.takeInputs(m_leftMotorSetpoint, m_rightMotorSetpoint);
    	setTimeout(m_duration);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return isTimedOut();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.drive.takeInputs(0, 0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	Robot.drive.takeInputs(0, 0);
    }
}
