// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc771.MyRobot.subsystems;

import org.usfirst.frc771.MyRobot.RobotMap;
import org.usfirst.frc771.MyRobot.commands.*;

import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Intake extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Encoder shooterQuadEncoder = RobotMap.intakeShooterQuadEncoder;
    private final SpeedController intakeMotor = RobotMap.intakeIntakeMotor;
    private final SpeedController leftMecanum = RobotMap.intakeLeftMecanum;
    private final SpeedController rightMecanum = RobotMap.intakeRightMecanum;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void intake(){
    	intakeMotor.set(0.5);
    	leftMecanum.set(0);
    	rightMecanum.set(0);
    }
    
    public void lowShoot(){
    	intakeMotor.set(-0.9);
    	leftMecanum.set(0.9);
    	rightMecanum.set(-0.9);
    }
    
    public void stopIntake(){
    	intakeMotor.set(0);
    	leftMecanum.set(0);
    	rightMecanum.set(0);
    }
}

